app = "multilingualnews"
primary_region = "yyz"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = false
  min_machines_running = 1
  processes = ["app"]

[checks]
  [checks.health]
    type = "http"
    interval = "15s"
    timeout = "3s"
    grace_period = "10s"
    method = "GET"
    path = "/health"

[processes]
  app = "gunicorn multilingualnews:app --bind 0.0.0.0:8080 --workers 1 --threads 2 --timeout 120"
